version : "3.9"

services:
  mongo:
    image: mongo:7
  
  rabbitmq:
    image: rabbitmq:3-management

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"

  test_runner:
    build: 
      context: .
      target: test
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://mongo:27017/testdb
      RABBITMQ_HOST: amqp://rabbitmq:5672
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      S3_ENDPOINT: http://localstack:4566
      S3_BUCKET: test-bucket
    depends_on:
      - mongo
      - rabbitmq
    # command: npm run test