version : "3.9"

services:
  mongo:
    image: mongo:7
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672-5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics","check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT=http://localstack:4566
      - S3_TEST_BUCKET=test-bucket
      - S3_BUCKET=test-bucket
    ports:
      - "4566:4566"

  test_runner:
    build: 
      context: .
      target: test
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://mongo:27017/testdb
      RABBITMQ_HOST: amqp://rabbitmq:5672
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      S3_ENDPOINT: http://localstack:4566
      S3_TEST_BUCKET: test-bucket
      S3_BUCKET: test-bucket
      TEST_QUEUE_NAME: file-processor-test
      TEST_DB_NAME: docflow_test
      TEST_IMAGE_PATH: /app/tests/uploads/
    depends_on:
        - mongo
        - rabbitmq
    # command: npm run test