name: CI

on:
  push:
    branches:
      - development
      - staging
  pull_request:
    branches:
      - development
      - staging

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run integration tests
        run: |
          sudo docker compose -f docker-compose.integration.yml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from test_runner
